### PR TITLE
Add support for compilation with ASAN/UBSAN

### PR DESCRIPTION
**Pull request by IvanNardi**
Add a CI job for testing it (shameless copied from picoquic)

### CODE REVIEW

**Review by huitema — COMMENTED** [review]
Looks good, but how did you test it?
Should we add a github action to execute the test suite using ASAN-UBSAN?

**Comment by IvanNardi** [comment]
@huitema, I *think* there is a missing `quicdoq_delete_query_ctx()`, but I am not sure about the right place to add it...

**Comment by huitema** [comment]
Great! Finding this kind of leaks is exactly why we want to run the sanitizers. I am on the road this weekend -- visiting my granddaughter and her parents. Will be back Monday and will try to look at it if you have not found the leak before that.

**Comment by huitema** [comment]
@IvanNardi I verified the memory allocation/free. There was two embarrassing mistakes:

1- In `quicdoq_delete_stream_ctx` there was a comment stating _"If this is a server stream, delete the query"_ but the corresponding code was not there yet.

2- The code in `quicdoq_delete_udp_ctx` was properly cancelling the UDP queries queued in the UDP context, but was not freeing the UDP context itself.

Good that we fixed that! Merging the PR now.

**Comment by IvanNardi** [comment]
@huitema , thanks for the follow-up!

**Pull request merged**
